import type { ShippingPool } from "./types";

export const mockShippingPools: ShippingPool[] = [
  {
    id: "pool-1",
    name: "Q1 2024",
    quarter: "Q1 2024",
    departurePort: "Yokohama",
    arrivalPort: "Vancouver",
    departureDate: "2024-03-15",
    arrivalDate: "2024-04-05",
    capacity: 40,
    filled: 34,
    teuReserved: 34,
    teuCapacity: 40,
    participants: 26,
    status: "filling",
    costPerVehicle: 1200,
    savingsVsSingle: 200,
    recentAdditions: [
      "1999 Nissan Skyline R34 GT-R",
      "1993 Toyota Supra RZ",
      "2001 Subaru Impreza WRX STI",
    ],
    timeline: {
      inspection: 2,
      loading: 3,
      transit: 21,
      customs: 5,
    },
  },
  {
    id: "pool-2",
    name: "Q2 2024",
    quarter: "Q2 2024",
    departurePort: "Yokohama",
    arrivalPort: "Los Angeles",
    departureDate: "2024-06-15",
    arrivalDate: "2024-07-08",
    capacity: 40,
    filled: 18,
    teuReserved: 18,
    teuCapacity: 40,
    participants: 15,
    status: "filling",
    costPerVehicle: 1450,
    savingsVsSingle: 150,
    recentAdditions: [
      "1996 Mazda RX-7 Type R",
      "1998 Honda NSX Type S",
      "2000 Toyota MR2 Turbo",
    ],
    timeline: {
      inspection: 2,
      loading: 3,
      transit: 23,
      customs: 4,
    },
  },
  {
    id: "pool-3",
    name: "Q3 2024",
    quarter: "Q3 2024",
    departurePort: "Kobe",
    arrivalPort: "Seattle",
    departureDate: "2024-09-15",
    arrivalDate: "2024-10-04",
    capacity: 40,
    filled: 8,
    teuReserved: 8,
    teuCapacity: 40,
    participants: 6,
    status: "filling",
    costPerVehicle: 1500,
    savingsVsSingle: 0,
    recentAdditions: [
      "2002 Honda Civic Si",
      "1997 Nissan 300ZX",
      "2003 Toyota Celica",
    ],
    timeline: {
      inspection: 2,
      loading: 3,
      transit: 19,
      customs: 4,
    },
  },
];

