import type {
  VehicleSummary,
  AgentProfile,
  Auction,
  ShippingPool,
  Testimonial,
  CommunityStory,
  FAQ,
} from "./types";

export const mockVehicles: VehicleSummary[] = [
  {
    id: "1",
    year: 2023,
    make: "Nissan",
    model: "Skyline GT-R",
    mileage: 18500,
    condition: "mint",
    jpPrice: 15200000,
    estimatedLandedCost: 28500,
    primaryImage:
      "https://images.unsplash.com/photo-1594987355808-fcf52a7b4e38?w=800&q=80",
    seller: {
      id: "seller-1",
      name: "Tokyo Motors",
      rating: 4.8,
      reviewCount: 127,
      verified: true,
    },
    featured: true,
  },
  {
    id: "2",
    year: 1993,
    make: "Toyota",
    model: "Supra A90",
    mileage: 58000,
    condition: "excellent",
    jpPrice: 8900000,
    estimatedLandedCost: 22300,
    primaryImage:
      "https://images.unsplash.com/photo-1492496694663-1a6a6f4e63f2?w=800&q=80",
    seller: {
      id: "seller-2",
      name: "Kyoto Classic",
      rating: 4.9,
      reviewCount: 203,
      verified: true,
    },
    featured: true,
  },
  {
    id: "3",
    year: 1996,
    make: "Mazda",
    model: "RX-7 FD",
    mileage: 92000,
    condition: "excellent",
    jpPrice: 7800000,
    estimatedLandedCost: 20500,
    primaryImage:
      "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800&q=80",
    seller: {
      id: "seller-3",
      name: "Osaka Auto",
      rating: 4.7,
      reviewCount: 156,
      verified: true,
    },
    featured: true,
  },
];

export const mockAgents: AgentProfile[] = [
  {
    id: "agent-1",
    name: "Yuki Tanaka",
    rating: 4.9,
    dealCount: 127,
    responseTime: 120,
    languages: ["ja", "en"],
    specialties: ["Sports Cars", "Auction Houses", "Export Documentation"],
    status: "online",
    queueLength: 2,
    location: "Tokyo, Japan",
    since: 2019,
    successRate: 98.5,
    typicalRange: "$200-500k",
    avgSavings: 3200,
    bio: "Specializing in high-performance JDM vehicles with 8+ years of export experience. Fluent in technical automotive terminology and has direct relationships with major auction houses including USS...",
  },
  {
    id: "agent-2",
    name: "Hiroshi Sato",
    rating: 4.8,
    dealCount: 89,
    responseTime: 240,
    languages: ["ja", "en", "ko"],
    specialties: ["Classic Cars", "Restoration Projects", "Parts Sourcing"],
    status: "online",
    queueLength: 0,
    location: "Osaka, Japan",
    since: 2017,
    successRate: 96.8,
    typicalRange: "$50-200k",
    avgSavings: 2800,
    bio: "Expert in vintage JDM vehicles and restoration projects with 12+ years experience. Maintains extensive network with classic car dealers, restoration shops, and parts suppliers across Japan.",
  },
  {
    id: "agent-3",
    name: "Akiko Yamamoto",
    rating: 4.9,
    dealCount: 156,
    responseTime: 60,
    languages: ["ja", "en", "zh"],
    specialties: ["Drift Cars", "Modified Vehicles", "Track Cars"],
    status: "online",
    queueLength: 1,
    location: "Yokohama, Japan",
    since: 2018,
    successRate: 99.2,
    typicalRange: "$30-150k",
    avgSavings: 2400,
    bio: "Passionate about modified JDM vehicles and drift culture with deep connections in the tuning community. Specializes in performance builds and track-ready vehicles with verified...",
  },
  {
    id: "agent-4",
    name: "Kenji Nakamura",
    rating: 4.7,
    dealCount: 73,
    responseTime: 360,
    languages: ["ja", "en"],
    specialties: ["Luxury Vehicles", "Rare Models", "Investment Grade"],
    status: "online",
    queueLength: 0,
    location: "Nagoya, Japan",
    since: 2020,
    successRate: 97.3,
    typicalRange: "$100k+",
    avgSavings: 4100,
    bio: "Focused on rare and investment-grade JDM vehicles with meticulous attention to documentation and authenticity verification. Specializes in low-mileage, museum-quality examples.",
  },
  {
    id: "agent-5",
    name: "Mei Suzuki",
    rating: 4.9,
    dealCount: 203,
    responseTime: 180,
    languages: ["ja", "en", "pt"],
    specialties: ["Kei Cars", "Daily Drivers", "Budget Imports"],
    status: "online",
    queueLength: 0,
    location: "Fukuoka, Japan",
    since: 2019,
    successRate: 98.8,
    typicalRange: "$5-50k",
    avgSavings: 1800,
    bio: "Specialist in affordable JDM imports including Kei cars and reliable daily drivers. Excellent at finding hidden gems and budget-friendly options without compromising quality.",
  },
  {
    id: "agent-6",
    name: "Takeshi Watanabe",
    rating: 4.8,
    dealCount: 94,
    responseTime: 300,
    languages: ["ja", "en", "es"],
    specialties: ["Trucks & Vans", "Commercial Vehicles", "4WD Specialists"],
    status: "online",
    queueLength: 0,
    location: "Sendai, Japan",
    since: 2019,
    successRate: 96.5,
    typicalRange: "$15-80k",
    avgSavings: 2200,
    bio: "Expert in Japanese commercial vehicles, trucks, and 4WD systems. Specializes in Delica vans, Hiace, and mini trucks popular for adventure and commercial use.",
  },
];

export const mockAuctions: Auction[] = [
  {
    id: "auction-1",
    vehicle: mockVehicles[0],
    currentBid: 1450000,
    timeRemaining: 225,
    bidCount: 12,
    status: "ending_soon",
    eligibleCountries: ["USA", "Canada"],
    endsAt: new Date(Date.now() + 225 * 1000).toISOString(),
    inspectionReportAvailable: true,
  },
  {
    id: "auction-2",
    vehicle: mockVehicles[1],
    currentBid: 3200000,
    timeRemaining: 743,
    bidCount: 8,
    status: "live",
    eligibleCountries: ["USA", "Canada"],
    endsAt: new Date(Date.now() + 743 * 1000).toISOString(),
    inspectionReportAvailable: true,
  },
];

export const mockShippingPools: ShippingPool[] = [
  {
    id: "pool-1",
    name: "Q2 2024 - West Coast",
    departurePort: "Yokohama",
    arrivalPort: "Long Beach",
    departureDate: "2024-04-05",
    arrivalDate: "2024-04-19",
    capacity: 24,
    filled: 8,
    status: "filling",
    costPerVehicle: 1100,
    savingsVsSingle: 5300,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Alex Chen",
    location: "Seattle, WA",
    vehicle: "R34 Skyline GTR",
    quote:
      "I was scared. First import, didn't know anyone in Japan, didn't trust online strangers. JDM Collective connected me with an agent who handled EVERYTHING. Cost $4k less than local imports, car arrived perfect. Game changer.",
    rating: 5,
    verified: true,
  },
  {
    id: "test-2",
    name: "Kenji Yamamoto",
    location: "Tokyo, Japan",
    vehicle: "Tokyo Motors",
    quote:
      "As a dealer, I was skeptical. But the verification process was fair, and suddenly I have access to 45,000 North American buyers. Turned my 20-car inventory into 8 sales/month business. Revenue tripled.",
    rating: 5,
    verified: true,
  },
  {
    id: "test-3",
    name: "Priya Kapoor",
    location: "Toronto, ON",
    vehicle: "Toyota Supra A90",
    quote:
      "The quarterly pool saved my family $3,200. We joined with 3 other Canadian importers shipping to Vancouver. Logistics was seamless. My wife got her dream Supra for $22k instead of $25k. And I got to pick the delivery date!",
    rating: 5,
    verified: true,
  },
];

export const mockCommunityStories: CommunityStory[] = [
  {
    id: "story-1",
    author: {
      name: "Alex Chen",
      location: "Seattle, WA",
    },
    vehicle: "R34 Skyline GTR Build",
    quote: "Childhood dream to reality",
    views: 3427,
    likes: 1240,
    comments: 156,
    importedCost: 28500,
  },
  {
    id: "story-2",
    author: {
      name: "Marcus Thompson",
      location: "Los Angeles, CA",
    },
    vehicle: "1993 Toyota Supra A60",
    quote: "The investment that paid off",
    views: 8942,
    likes: 3204,
    comments: 428,
    importedCost: 22300,
  },
  {
    id: "story-3",
    author: {
      name: "Priya Kapoor",
      location: "Toronto, ON",
    },
    vehicle: "1999 Honda Civic Type-R",
    quote: "Daily driver perfection",
    views: 2156,
    likes: 912,
    comments: 89,
    importedCost: 12800,
  },
];

export const mockFAQs: FAQ[] = [
  {
    id: "faq-1",
    question: "Is it legal to import JDM cars?",
    answer:
      "Yes, if the car is 25+ years old in the USA (EPA exemption) or 15+ years in Canada. We automatically check eligibility and show green/yellow badges on all listings. Our agents guide you through the legal requirements for YOUR state/province.",
    category: "legal",
  },
  {
    id: "faq-2",
    question: "How does escrow protect me?",
    answer:
      "Your payment is held by a trusted third party and released at each milestone after verification. If anything goes wrong, your money stays protected.",
    category: "payment",
  },
  {
    id: "faq-3",
    question: "What if I don't like the car?",
    answer:
      "We have a 30-day return window if the vehicle doesn't match the description or has safety issues.",
    category: "returns",
  },
  {
    id: "faq-4",
    question: "Can I finance through you?",
    answer:
      "Yes, we've partnered with auto lenders offering flexible financing. Get pre-qualified in minutes.",
    category: "financing",
  },
  {
    id: "faq-5",
    question: "What's the actual timeline?",
    answer:
      "8-12 weeks from browse to delivery: Discovery (1 week), Inspection (1 week), Shipping (4-6 weeks), Customs (1 week), Delivery (1 week).",
    category: "timeline",
  },
];

